#!/usr/bin/env bash
export TERM=dumb
set -e
oldrev=$1
newrev=$2

run() {
  [ -x $1 ] && $1 $oldrev $newrev
}

#Output changes
echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)
umask 002

sudo chown -R app:www-data ./storage/
sudo chmod -R 775 ./storage/

#Update any git submodules
git submodule sync && git submodule update --init --recursive

#Update and install packages via composer
echo -e "\nUpdating Composer & installing packages...\n"
sudo composer self-update
composer install --no-dev